### ISSUE TITLE
Trouble in --recursive cloning

### ISSUE THREAD

**Issue by classiccoding** [Kroc/EliteDX#24]
If i try to clone the repository recursively (in cygwin), i get a fatal error:

$ git clone --recursive https://github.com/Kroc/EliteDX
Cloning into 'EliteDX'...
remote: Counting objects: 585, done.
remote: Compressing objects: 100% (355/355), done.
remote: Total 585 (delta 411), reused 384 (delta 210), pack-reused 0
Receiving objects: 100% (585/585), 533.07 KiB | 132.00 KiB/s, done.
Resolving deltas: 100% (411/411), done.
Checking connectivity... done.
fatal: no submodule mapping found in .gitmodules for path 'bin/mkd64'

**Comment by Kroc** [comment]
Ah, yes, that folder should not have been included in the repository, I'll remove it now! Sorry for the inconvenience.

**Comment by Kroc** [comment]
That should be fixed now -- the mkd64 folder is downloaded by the setup script; it's not actually supposed to be a part of the repository; there are no intended submodules, so you don't need to use `--recursive`
